### ISSUE TITLE
Does this python package work on Windows 11?

### ISSUE THREAD

**Issue by RobertASu1** [barahona-research-group/RamanSPy#22]
Does anyone know if this python package works on Windows, because I've spent a lot of time trying to figure out how to get some Github modules or packages to work on Windows 11 only to find out they won't, and don't want to waste a lot of time trying to figure it out if it won't work.

**Comment by dgeorgiev21** [comment]
Hi @RobertASu1 

Thank you for reaching out with your concern.

This is the first report of this kind, and the package should work on Windows 11.

If you're encountering issues, could you please provide more details, such as your Python version and any error messages you're seeing? This will help us troubleshoot the problem more effectively.

We appreciate your patience and thank you for bringing this to our attention.

**Comment by RobertASu1** [comment]
No, I haven't even attempted to install the program yet.  I was just asking
before attempting, because I spent a lot of time trying to install various
github packages on my Windows system, only to find out it's difficult or
impossible to do so, so before I make another attempt I want to be sure
it's possible and don't waste anymore time.  Thanks for the fast response.

**Comment by dgeorgiev21** [comment]
Please feel free to try it out! Installation should be as simple as running:
```console
pip install ramanspy
```

If you encounter any issues, especially with conflicting package dependencies, try creating a clean environment first.

Let us know how it goes—we’ll leave this issue open for now in case others want to chime in. If everything works smoothly, we’d appreciate it if you could close the issue.

---
If you find `RamanSPy` useful, please consider starring the project on `GitHub`! Your support means a lot!
